  version: '3'
  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    web:
      build: .
      command:
        - ./docker-entrypoint.sh
      environment:
        - HTTP_PORT=${HTTP_PORT:-8000}
      volumes:
        - .:/django-docker
      ports:
        - "${HTTP_PORT:-8000}:${HTTP_PORT:-8000}"
      depends_on:
        - db