# Generated by Django 3.0.7 on 2020-06-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecodedJWT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iat', models.IntegerField()),
                ('jti', models.TextField()),
                ('payload', models.TextField()),
            ],
        ),
    ]
